-- To-Do list Sample Database Data

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

USE yk_todo;

--
-- Data for table tasks
--

SET AUTOCOMMIT=0;
INSERT INTO tasks VALUES (NULL,'Finish database class.', NULL),(NULL,'Check email.', NULL),(NULL,'Call Bob at 3PM.', NULL),(NULL,'Review documentation.', NULL);
COMMIT;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;